### ISSUE TITLE
Presenting point-in-time understanding of dependencies for objectives in Plan Review

### ISSUE THREAD

**Issue by awaldow** [destacey/Moda#116]
Something we've run into is the fact that our team has our own objectives (things we want to do, services we want to create), and then we are heavily depended on by other teams to support their objectives within our disciplines. I think having some sort of team dependency map on an objective can help highlight (and possibly visualize, later) these dependencies and reveal dependency overload between our teams.

This could also evolve into a situation where you set up some dependencies during Planning as your best effort understanding, and then over the course of the PI suddenly work items appear for teams not on that list, and they can then be added as "discovered" vs "defined" to help inform over objectives like that in the future.

Maybe this is cutting against the notion of what objectives and PIs are meant to be but I think it's a little bit of metadata that may help.

**Comment by destacey** [comment]
This will come as we start syncing working items from DevOps.  Once that info is in the system, we will be able to add work items to the objectives.  The objectives will then be able to display the dependency info from those underlying work items.  The dependencies will also indicate RAG status (red, amber, green) based on the following:
- Green: both dependencies are planned in an iteration and the predecessor is in an iteration that finishes before the successor
- Amber: 
   - one or both of the dependencies have not been planned in an iteration or
   - both dependencies are planned in an iteration and the both are planned in iterations that finish at the same time
- Red: both dependencies are planned in an iteration and the predecessor is in an iteration that finishes after the successor
